apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cursedbot-build
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: cursedbot-build-
    spec:
      serviceAccountName: trigger-account
      pipelineRef:
        name: docker-build-pipeline
      workspaces:
        - name: source
          persistentVolumeClaim:
            claimName: workspace-pvc
        - name: auth-directory
          secret:
            secretName: git-password
        - name: dockerconfig
          secret:
            secretName: docker-config
      params:
        - name: url
          value: "https://github.com/adamsong/CursedBot-ts.git"
        - name: image-name
          value: "ghcr.io/adamsong/cursedbot-ts"
        - name: infra-url
          value: "https://adamsong@github.com/adamsong/prod-chart.git"
        - name: infra-path
          value: "charts/cursedbot/image.yaml"
