apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cursedbot
spec:
  serviceAccountName: trigger-account
  triggers:
  - name: pullrequest-build
    template:
      ref: cursedbot-build