{{- if .Values.cursedbot.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: cursedbot-secret
stringData:
{{- if .Values.cursedbot.secrets }}
{{ toYaml .Values.cursedbot.secrets | indent 2 }}
{{- end }}
{{- end }}