apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-image
  labels:
    app.kubernetes.io/version: "0.6"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/categories: Git
    tekton.dev/tags: git
    tekton.dev/displayName: "Update image.yaml with new image"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task updates and commits image.yaml with the new image.
  params:
    - name: IMAGE_DIGEST
      description: Digest of the image just built.
    - name: IMAGE_URL
      description: URL of the image just built.
    - name: image-yaml-path
      description: Path to the image.yaml file.
    - name: gitInitImage
      description: The image providing the git-init binary that this Task runs.
      type: string
      default: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.29.0"
    - name: userHome
      description: |
        Absolute path to the user's home directory. Set this explicitly if you are running the image as a non-root user or have overridden
        the gitInitImage param with an image containing custom user configuration.
      type: string
      default: "/tekton/home"
  workspaces:
    - name: source
      description: Holds the git source.
    - name: auth-directory
  steps:
    - name: render-yaml-and-commit
      workingDir: $(workspaces.source.path)
      image: "$(params.gitInitImage)"
      env:
      - name: HOME
        value: "$(params.userHome)"
      script: |
        set -e -x

        git config --global user.email "<>"
        git config --global user.name "Tekton Build Tool"

        cat << EOF > $(params.image-yaml-path)
        # Autogenerated by build script
        image:
          name: $(params.IMAGE_DIGEST)
          newName: $(params.IMAGE_URL)
        EOF
        git add $(params.image-yaml-path)
        git commit -m "Update build to $(params.IMAGE_DIGEST)"
        chmod +x $(workspaces.auth-directory.path)/auth_helper.sh
        GIT_ASKPASS=$(workspaces.auth-directory.path)/auth_helper.sh git push origin HEAD:master
