{{- if .Values.eventlistener.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.eventlistener.name }}
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - tekton.adamsogm.ml
      secretName: tekton-cert
  rules:
  - host: tekton.adamsogm.ml
    http:
      paths:
      - path: /webhook
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ printf "el-%s" .Values.eventlistner.name }}
            port:
              name: http-listener
{{- end }}