oauth2-proxy:
  extraArgs:
    provider: github
    whitelist-domain: admsogm.ml
    cookie-domain: adamsogm.us
    redirect-url: https://auth.adamsogm.us/oauth2/callback
    github-user: adamsong

  ingress:
    enabled: true
    path: /
    hosts:
      - auth.adamsogm.us
    annotations:
        kubernetes.io/ingress.class: public
        cert-manager.io/cluster-issuer: letsencrypt-production
    tls:
      - hosts:
          - auth.adamsogm.us
        secretName: auth-cd-tls