oauth2-proxy:
  extraArgs:
    provider: github
    whitelist-domain: .admsogm.ml
    cookie-domain: .adamsogm.ml
    redirect-url: https://auth.adamsogm.ml/oauth2/callback
    github-repo: adamsogm/cursedbot

  ingress:
    enabled: true
    path: /
    hosts:
      - auth.adamsogm.ml
    tls:
      - hosts:
          - auth.adamsogm.ml
        secretName: auth-cd-tls