apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/adamsong/prod-chart.git
    targetRevision: HEAD
    helm:
      valueFiles:
 #       - secrets+age-import:///helm-secrets-private-keys/key.txt?secrets.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true