{{- if .Values.apps.cursedbot.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cursedbot
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cursedbot
  project: default
  source:
    path: charts/cursedbot
    repoURL: https://github.com/adamsong/prod-chart.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/key.txt?secrets.yaml
        - image.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{- end }}