{{- if .Values.apps.argocd.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: external-ip
  namespace: proxy
spec:
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 8080
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
---
kind: Endpoints
apiVersion: v1
metadata:
  name: external-ip
  namespace: proxy
subsets:
  - addresses:
      - ip: 10.1.103.192
    ports:
      - name: app
        port: 8080
        protocol: TCP
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: external-service
  namespace: proxy
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - proxy.adamsogm.us
      secretName: proxy-tls
  rules:
    - host: proxy.adamsogm.us
      http:
        paths:
          - path: /
            backend:
              serviceName: external-ip
              servicePort: 80 
{{- end }}