{{- if .Values.apps.tekton.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-generic
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/adamsong/prod-chart.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{- end }}