argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      url: https://argo.adamsogm.ml
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
    ingress:
      enabled: true
      hosts: ["argo.adamsogm.ml"]
      annotations:
        kubernetes.io/ingress.class: public
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls:
        - hosts:
            - argo.adamsogm.ml
          secretName: argo-cd-tls