argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      url: https://argocd.adamsogm.ml
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
    ingress:
      enabled: true
      hosts: ["adamsogm.ml"]
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - hosts:
            - argocd.yogstation.net